-- MySQL Script generated by MySQL Workbench
-- 11/20/17 12:15:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema INFI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema INFI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `INFI` DEFAULT CHARACTER SET utf8 ;
USE `INFI` ;

-- -----------------------------------------------------
-- Table `INFI`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INFI`.`subjects` ;

CREATE TABLE IF NOT EXISTS `INFI`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lvnr` CHAR(100) NOT NULL,
  `title` CHAR(100) NOT NULL,
  `groups_required` INT NOT NULL,
  `hours` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INFI`.`teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INFI`.`teachers` ;

CREATE TABLE IF NOT EXISTS `INFI`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `f_name` CHAR(100) NOT NULL,
  `l_name` CHAR(100) NOT NULL,
  `short` CHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INFI`.`lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INFI`.`lessons` ;

CREATE TABLE IF NOT EXISTS `INFI`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_teachers` INT NOT NULL,
  `hours` INT NOT NULL,
  `group` CHAR(100) NOT NULL,
  `id_subjects` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lessons_teachers1_idx` (`id_teachers` ASC),
  INDEX `fk_lessons_subjects1_idx` (`id_subjects` ASC),
  CONSTRAINT `fk_lessons_teachers1`
    FOREIGN KEY (`id_teachers`)
    REFERENCES `INFI`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_subjects1`
    FOREIGN KEY (`id_subjects`)
    REFERENCES `INFI`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Testdaten

INSERT INTO `teachers` (`id`, `f_name`, `l_name`, `short`) VALUES (NULL, 'Katzengruber', 'Leo', 'leka'), (NULL, 'Blank', 'Michael', 'mibl'), (NULL, 'Gabsi', 'Lukas', 'luga');
INSERT INTO `subjects` (`id`, `lvnr`, `title`, `groups_required`, `hours`) VALUES (NULL, '100-3342', 'Betriebstechnik', '2', '10'), (NULL, '100-3378', 'Automatisierungstechnik', '3', '5'), (NULL, '100-3367', 'Laboratorium - INFI', '1', '20'), (NULL, '100-3365', 'Theorie - INFI', '1', '10'), (NULL, '100-3387', 'Laboratorium - Robotik', '28', '15');
INSERT INTO `lessons` (`id`, `id_teachers`, `hours`, `group`, `id_subjects`) VALUES (NULL, '1', '20', '30', '2'), (NULL, '1', '20', '30', '3'), (NULL, '2', '10', '100', '5'), (NULL, '3', '20', '150', '4'), (NULL, '3', '5', '1', '1');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
